import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(fileURLToPath(new URL('..', import.meta.url)));
const workerPath = resolve(root, 'apps/relay/src/worker.mjs');
const configPath = resolve(root, 'wrangler.toml');
const assetIndex = resolve(root, 'apps/web/dist/index.html');

test('Wrangler assets routing sends API, health and OAuth paths to the Worker', async (t) => {
  // The built client is intentionally not generated by the unit-test command. CI and release
  // checks run the web build first; keep a source checkout without dist usable for unit tests.
  if (!existsSync(assetIndex)) {
    t.skip('apps/web/dist is absent; run the web build before the deployment routing check');
    return;
  }

  let unstableDev;
  try {
    ({ unstable_dev: unstableDev } = await import('wrangler'));
  } catch (error) {
    // Some restricted Windows sandboxes disallow Wrangler's esbuild/workerd child process. The
    // test remains required in normal CI, where it exercises the actual Wrangler assets router.
    if (error?.code === 'EPERM') {
      t.skip('Wrangler local runtime cannot spawn in this sandbox');
      return;
    }
    throw error;
  }

  let dev;
  try {
    dev = await unstableDev(workerPath, {
      config: configPath,
      local: true,
      persist: false,
      port: 0,
      logLevel: 'error',
    });
  } catch (error) {
    if (error?.code === 'EPERM') {
      t.skip('Wrangler local runtime cannot spawn in this sandbox');
      return;
    }
    throw error;
  }

  try {
    const base = /^https?:\/\//i.test(dev.address) ? dev.address : `http://${dev.address}:${dev.port}`;
    const get = (path) => fetch(`${base}${path}`);

    // Before the run_worker_first fix, this path was served by the SPA fallback as HTML (200).
    // The deployed Worker must receive it first and reject the missing Access assertion as JSON.
    const api = await get('/v1/dashboard');
    assert.equal(api.status, 401);
    assert.match(api.headers.get('content-type') || '', /^application\/json/i);
    assert.equal((await api.json()).error, 'unauthorized');

    const health = await get('/healthz');
    assert.equal(health.status, 200);
    assert.match(health.headers.get('content-type') || '', /^application\/json/i);
    assert.equal((await health.json()).ok, true);

    const callback = await get('/oauth/android/callback?state=state&code=one-use-code');
    assert.equal(callback.status, 200);
    const callbackHtml = await callback.text();
    assert.match(callbackHtml, /window\.location\.replace/);
    assert.match(callbackHtml, /dev\.peteryhs\.unidash:\/oauth\/callback\?code=one-use-code(?:&|\\u0026)state=state/);

    const shell = await get('/');
    assert.equal(shell.status, 200);
    assert.match(shell.headers.get('content-type') || '', /^text\/html/i);
    assert.match(await shell.text(), /<html\b/i);

    // Unknown client-side navigation also stays on the SPA shell while API paths remain Worker
    // owned, which is the production split needed by React Router.
    const navigation = await get('/settings/profile');
    assert.equal(navigation.status, 200);
    assert.match(navigation.headers.get('content-type') || '', /^text\/html/i);
    assert.match(await navigation.text(), /<html\b/i);
  } finally {
    await dev.stop();
  }
});
